---
- hosts: local
  gather_facts: true

  tasks:
    - name: Проверить наличие директории приложения
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Подтянуть изменения с гита
      include_role:
        name: git

    - name: Пересобрать Docker-образ и запустить
      include_role:
        name: docker
