---
- hosts: local
  gather_facts: true

  tasks:
    - name: Проверить наличие директории приложения
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Пересобрать Docker-образ
      command: docker-compose -f "{{ docker_compose_file }}" build
      args:
        chdir: "{{ app_dir }}"

    - name: Перезапустить контейнеры
      command: docker-compose -f "{{ docker_compose_file }}" up -d
      args:
        chdir: "{{ app_dir }}"
